# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-30 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('l', 'Limites'), ('d', 'Derivadas'), ('i', 'Integrales'), ('ed', 'Ecuaciones Diferenciales')], max_length=2)),
                ('problema', models.CharField(max_length=1000)),
                ('solucion', models.CharField(max_length=1000)),
            ],
        ),
    ]
